[project]
name            = "image-localizer"
version         = "0.1.0"
description     = "Image localization pipeline (NetVLAD→FAISS→HLoc)"
authors         = [{ name="Dariya Bakshinska", email="darya.bakshinska@farsightvision.com" }]
requires-python = ">=3.8"

dependencies = [
  # only pull the pip wheel on Linux
  # "faiss-cpu; sys_platform == 'linux'",
  "faiss-cpu",
  "pycolmap",
  "plyfile",
  "plotly",
  "Pillow",
  "numpy",
  "h5py",
  # "hloc @ git+https://github.com/cvg/Hierarchical-Localization.git@master"
  "hloc",
]

[project.optional-dependencies]
dev = [
  "jupyter",
  "scipy"
]

 [build-system]
 requires = ["hatchling"]
 build-backend = "hatchling.build"

 [tool.uv.sources]
 hloc = { git = "https://github.com/cvg/Hierarchical-Localization.git", rev = "master" }
