[build-system]
requires    = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name            = "image-localizer"
version         = "0.1.0"
description     = "Image localization pipeline (NetVLAD→FAISS→HLoc)"
authors         = [{ name="Dariya Bakshinska    ", email="darya.bakshinska@farsightvision.com" }]
requires-python = ">=3.8"
packages        = ["image_localizer"]
dependencies    = []