[tool.uv]
name        = "image-localizer"
version     = "0.1.0"
description = "Image localization pipeline (NetVLAD→FAISS→HLoc)"
authors     = ["Dariya Bakshinska <darya.bakshinska@farsightvision.com>"]

[tool.uv.dependencies]
faiss-cpu                   = "latest"
pycolmap                    = "latest"
plyfile                     = "latest"
plotly                      = "latest"
pillow                      = "latest"
numpy                       = "latest"
"Hierarchical-Localization" = { git = "https://github.com/cvg/Hierarchical-Localization.git", rev = "main" }
